name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main  # Inicia cuando subes cambios a la rama main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      #Validar repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
      #Instalar node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      #Instalar dependencias
      - name: Install dependencies
        run: npm ci
        working-directory: ./functions
      #Construir soluci√≥n
      - name: Build project
        run: npm run build
        working-directory: ./functions
      #Instalar firebase tools
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      #Desplegar
      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions --force
        working-directory: ./functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


